### ISSUE TITLE
Does this play well with browserify?

### ISSUE THREAD

**Issue by olalonde** [troygoode/node-require-directory#19]
Was wondering if this module breaks browserify builds?

**Comment by troygoode** [comment]
I haven't tried it, but I suspect it'll work as it is just issuing a bunch of `require`s under the hood. Can you let us know how it goes?

**Comment by mrgamer** [comment]
require(s) works indeed, but I think `fs.readDir` does not work.
substack (browserify creator) made a companion plugin for `bulk-require`, that is called [bulkify](https://github.com/substack/bulkify)

That plugin basically does the reading of files part in node.js and then leaves the execution of `require(s)` to browser javascript.

Based on that plugin it can be made another small plugin to make browserify work with this project.

I am :+1: for this because substack has too many projects going on and bulkify/bulk-require have less options than this one and less maintenance
